# Generated by Django 5.0.2 on 2026-03-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habitcompletion_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitcompletion',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='habitcompletion',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='habit_date_unique'),
        ),
    ]
