# Generated by Django 5.0.2 on 2026-03-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habitcompletion_comment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together=set(),
        ),
    ]
