# Generated by Django 5.0.2 on 2026-03-14 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название эмоции')),
                ('emoji', models.CharField(max_length=10, verbose_name='Эмодзи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'эмоция',
                'verbose_name_plural': 'Эмоции',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тега')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный тег')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(default='Без названия', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание записи')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Достижения дня')),
                ('difficulties', models.TextField(blank=True, null=True, verbose_name='Трудности дня')),
                ('tomorrow_plans', models.TextField(blank=True, null=True, verbose_name='Планы на завтра')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.emotion', verbose_name='Настроение дня')),
                ('tags', models.ManyToManyField(blank=True, to='diary.tag', verbose_name='Теги дня')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date', '-created'],
            },
        ),
    ]
